# Generated by Django 5.0.7 on 2024-07-17 02:44

import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to=myapi.models.upload_path),
        ),
    ]
