# Generated by Django 5.0.7 on 2024-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to='music'),
        ),
    ]
