# Generated by Django 5.0.7 on 2024-07-18 01:21

import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to=myapi.models.upload_soundFile_path),
        ),
    ]
